name: Build and Deploy to EC2

on:
  push:
    branches: [ "chore/release-test-hey" ]
  pull_request:
    branches: [ "chore/release-test-hey" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: make other application-{profile}.yml
        run: |
          touch ./application-config.yml
          echo "${{ secrets.CONFIG }}" > ./application-config.yml
          
          touch ./application-db.yml
          echo "${{ secrets.DB }}" > ./application-db.yml
          
          touch ./application-file.yml
          echo "${{ secrets.FILE }}" > ./application-file.yml
          
          touch ./application-github.yml
          echo "${{ secrets.GITHUB }}" > ./application-github.yml
          
          touch ./application-jwt.yml
          echo "${{ secrets.JWT }}" > ./application-jwt.yml
          
          touch ./application-oauth.yml
          echo "${{ secrets.OAUTH }}" > ./application-oauth.yml
          
          touch ./application-payment.yml
          echo "${{ secrets.PAYMENT }}" > ./application-payment.yml


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        run: ./gradlew build test
